---


- name: "Baixando repositórios privados de {{ git_root_url }}/{{ git_username }} para {{ local_repos_root }}"
  git:
    repo: '{{ url_protocol }}://{{ git_username | urlencode }}:{{ git_pass | urlencode }}@{{ git_root_url }}/{{ git_username }}/{{ item }}.git'
    dest: '{{ local_repos_root }}/{{ item }}'
  with_items: "{{ repo_names }}"